---
title: "R Notebook"
output: html_notebook
---

```{r}
donations2013= readRDS("D:/527- Data Mining/TUN Data Challenge/DatasetsDonations2013.rds")
participants = readRDS("D:/527- Data Mining/TUN Data Challenge/Datasets/participants.rds")

```

```{r}
library(httr)
library(RCurl)
library(wordcloud)
library(ROAuth)
library(stringr)
library(SnowballC)
library(tm)
library(dplyr)
library(plyr)
library(RColorBrewer)
```


```{r}
mycorpus = VCorpus(VectorSource(participants$`Participant Connection to MS`)) 
mycorpus = tm_map(mycorpus,PlainTextDocument)
mycorpus = tm_map(mycorpus,removePunctuation)
mycorpus = tm_map(mycorpus, removeWords,stopwords(kind = "en"))
#mycorpus = tm_map(mycorpus,stemDocument)
pal = brewer.pal(8,"Dark2")
```

```{r}

dtm <- TermDocumentMatrix(mycorpus)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)
set.seed(1234)
```

```{r}
wordcloud(words = d$word, freq = d$freq, min.freq = 1,max.words=200, random.order=FALSE,colors=brewer.pal(8, "Dark2"))
```

```{r}
wordcloud(names(v), v, min.freq = 3)
```

